model:
  base_learning_rate: 1.0e-05
  target: ldm.models.autoencoder.DinoDecoder
  params:
    monitor: "val/rec_loss"
    embed_dim: 8

    ddconfig:
      z_channels: 8
      resolution: [480, 640]
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,4,8]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [[60,80]]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    num_workers: 0
    shuffle_val_dataloader: false
    batch_size: 2
    wrap: True
    train:
      target: ldm.data.vs_random.VsImageDataset
      params:
        img_size: [480, 640]
        data_root: "/yuxi/data/vs/good_random_data_single"
        data_flist: "train_img.flist"
    validation:
      target: ldm.data.vs_random.VsImageDataset
      params:
        data_root: "/yuxi/data/vs/good_random_data_single"
        img_size: [480, 640]
        data_flist: "val_img.flist"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 5000
        val_batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 6
