model:
  base_learning_rate: 1e-5
  target: ldm.models.diffusion.dino_ddpm.DinoLatentDiffusionSingle
  params:
    ckpt_path: logs/2025-01-19T12-02-37_screwdriver_sim_ldm/checkpoints/epoch=000122.ckpt
    linear_start: 0.0008
    linear_end: 0.012
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: segmentation
    image_size:
    - 30
    - 40
    channels: 4
    concat_mode: False
    monitor: val/loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.005
        lr_max: 0.01
        # lr_max: 0.001
        lr_min: 0.001
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size:
        - 30
        - 40
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 4
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        num_heads: 16
        use_spatial_transformer: true
        transformer_depth: 2
        context_dim: 384
        resblock_updown: true

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: logs/2025-01-18T21-17-48_screwdriver_sim/checkpoints/epoch=000055.ckpt
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1
            disc_weight: 0.5
        ddconfig:
          double_z: true
          z_channels: 4
          resolution:
          - 240
          - 320
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 8
          num_res_blocks: 2
          attn_resolutions:
          - - 30
            - 40
          dropout: 0.0
    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: true
    num_workers: 0
    train:
      target: ldm.data.vs.VsDataset
      params:
        img_size:
        - 240
        - 320
        data_root: "/mnt/workspace/cyxovo/dataset/screwdriver_sim"
        data_flist: train_vs.flist
    validation:
      target: ldm.data.vs.VsDataset
      params:
        data_root: "/mnt/workspace/cyxovo/dataset/screwdriver_sim"
        img_size:
        - 240
        - 320
        data_flist: val_vs.flist

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 5000
        val_batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 4